version: '3.8'

services:
  mariadb:
    image: mariadb:10.11  # Specific version
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: serverless-test2
      MYSQL_USER: serverless
      MYSQL_PASSWORD: Qazxsw!@#
      MYSQL_RANDOM_ROOT_PASSWORD: '1'  # Alternative to fixed root password
      TZ: UTC  # Timezone
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf  # Custom config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  adminer:  # Optional database management tool
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
