version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    extra_hosts:
      - "kafka:127.0.0.1"
    
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: |
      bash -c "
      until kafka-topics --bootstrap-server kafka:9092 --list; do
        sleep 1
      done
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_deploy_function_s3_request --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_deploy_function_registry_request --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_delete_function_request --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_websocket --partitions 1 --replication-factor 1
      
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_delete_function_response --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_test_event_response --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_deploy_function_registry_response --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --topic knative_deploy_function_s3_response --partitions 1 --replication-factor 1
      kafka-topics --list --bootstrap-server kafka:9092
      "

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092